name: Run git-secrets

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  git-secrets:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main
    steps:
      - name: Checkout awslabs/git-secrets
        uses: actions/checkout@v4
        with:
          repository: awslabs/git-secrets
          path: git-secrets

      - name: Install git-secrets
        working-directory: git-secrets
        run: sudo make install

      - name: Checkout all commits
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: main

      - name: Display scan target
        run: git --no-pager log --all --format="%s %H"

      - name: Setting git-secrets
        run: |
          git secrets --install
          git secrets --register-aws

      - name: Scan repository
        run: |
          git secrets --scan-history

      - name: Send data to Slack workflow
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "compare_url": "${{ github.server_url }}/${{ github.repository }}/compare/${{ github.ref_name }}",
              "actions_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "author": "${{ github.actor }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
